package modelo;
// Generated 13 ene 2026, 8:47:05 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.ArrayList;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.query.Query;
import org.hibernate.Transaction;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.reto2.elorserv.HibernateUtil;

/**
 * Reuniones generated by hbm2java
 */
public class Reuniones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idReunion;
	private Users usersByAlumnoId;
	private Users usersByProfesorId;
	private String estado;
	private String estadoEus;
	private String idCentro;
	private String titulo;
	private String asunto;
	private String aula;
	private Timestamp fecha;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Centros centro;

	public enum EstadoReunion {
		PENDIENTE("pendiente"),
		ACEPTADA("aceptada"),
		DENEGADA("denegada"),
		CONFLICTO("conflicto");

		private final String value;

		EstadoReunion(String value) {
			this.value = value;
		}

		public String getValue() {
			return value;
		}

		public static EstadoReunion fromValue(String value) {
			if (value == null || value.isBlank()) {
				return null;
			}
			for (EstadoReunion estado : values()) {
				if (estado.value.equalsIgnoreCase(value)) {
					return estado;
				}
			}
			throw new IllegalArgumentException("Estado de reunión desconocido: " + value);
		}
	}

	public Reuniones() {
	}

	public Reuniones(int idReunion) {
		this.idReunion = idReunion;
	}

	public Reuniones(Users usersByAlumnoId, Users usersByProfesorId, String estado, String estadoEus, String idCentro,
			String titulo, String asunto, String aula, Timestamp fecha, Timestamp createdAt, Timestamp updatedAt) {
		this.usersByAlumnoId = usersByAlumnoId;
		this.usersByProfesorId = usersByProfesorId;
		this.estado = estado;
		this.estadoEus = estadoEus;
		this.idCentro = idCentro;
		this.titulo = titulo;
		this.asunto = asunto;
		this.aula = aula;
		this.fecha = fecha;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Reuniones(Integer idReunion2, Users alumnoConvertido, Users profesorConvertido, String estado2,
			String estadoEus2, String idCentro2, String titulo2, String asunto2, String aula2, Timestamp fecha2,
			Timestamp createdAt2, Timestamp updatedAt2, Centros centro) {
		this.idReunion = idReunion2;
		this.usersByAlumnoId = alumnoConvertido;
		this.usersByProfesorId = profesorConvertido;
		this.estado = estado2;
		this.estadoEus = estadoEus2;
		this.idCentro = idCentro2;
		this.titulo = titulo2;
		this.asunto = asunto2;
		this.aula = aula2;
		this.fecha = fecha2;
		this.createdAt = createdAt2;
		this.updatedAt = updatedAt2;
		this.centro = centro;
	}

	public Integer getIdReunion() {
		return this.idReunion;
	}

	public void setIdReunion(Integer idReunion) {
		this.idReunion = idReunion;
	}

	public Users getUsersByAlumnoId() {
		return this.usersByAlumnoId;
	}

	public void setUsersByAlumnoId(Users usersByAlumnoId) {
		this.usersByAlumnoId = usersByAlumnoId;
	}

	public Users getUsersByProfesorId() {
		return this.usersByProfesorId;
	}

	public void setUsersByProfesorId(Users usersByProfesorId) {
		this.usersByProfesorId = usersByProfesorId;
	}

	public String getEstado() {
		return this.estado;
	}

	public EstadoReunion getEstadoEnum() {
		return EstadoReunion.fromValue(this.estado);
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public void setEstado(EstadoReunion estadoEnum) {
		this.estado = estadoEnum != null ? estadoEnum.getValue() : null;
	}

	public String getEstadoEus() {
		return this.estadoEus;
	}

	public void setEstadoEus(String estadoEus) {
		this.estadoEus = estadoEus;
	}

	public String getIdCentro() {
		return this.idCentro;
	}

	public void setIdCentro(String idCentro) {
		this.idCentro = idCentro;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	public String getAula() {
		return this.aula;
	}

	public void setAula(String aula) {
		this.aula = aula;
	}

	public Timestamp getFecha() {
		return this.fecha;
	}

	public void setFecha(Timestamp fecha) {
		this.fecha = fecha;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}
	
	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}
	public Centros getCentro() {
		return this.centro;
	}

	public void setCentro(Centros centro) {
		this.centro = centro;
	}

	@JsonIgnore
	public Reuniones convertirReunion() {
	    Users alumnoConvertido = null;
	    Users profesorConvertido = null;
	    if (usersByAlumnoId != null) {
	        alumnoConvertido = usersByAlumnoId.convertirUsuario();
	    }
	    if (usersByProfesorId != null) {
	        profesorConvertido = usersByProfesorId.convertirUsuario();
	    }
	    if (centro == null && idCentro != null) {
	        centro = new Centros(Integer.parseInt(idCentro)).getCentroById();
	    }
	    return new Reuniones(getIdReunion(), alumnoConvertido, profesorConvertido, getEstado(),
	            getEstadoEus(), getIdCentro(), getTitulo(), getAsunto(), getAula(), getFecha(), getCreatedAt(),
	            getUpdatedAt(),centro);
	}
	@JsonIgnore
	public static ArrayList<Reuniones> getAllReuniones() {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
		String hql = "from Reuniones";
		Query<Reuniones> q = session.createQuery(hql, Reuniones.class);
		ArrayList<Reuniones> reunionesConvertidas = new ArrayList<Reuniones
				>();
		for (Reuniones reunion : q.list()) {
			reunionesConvertidas.add(reunion.convertirReunion());
		}
		return reunionesConvertidas;
		
	}
	public static ArrayList<Reuniones> getReunionesByUserID(int idUser) {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
		String hql = "from Reuniones where usersByAlumnoId.id = :userID or usersByProfesorId.id = :userID";
		Query<Reuniones> q = session.createQuery(hql, Reuniones.class);
		q.setParameter("userID", idUser);
		ArrayList<Reuniones> reunionesConvertidas = new ArrayList<Reuniones
				>();
		for (Reuniones reunion : q.list()) {
			reunionesConvertidas.add(reunion.convertirReunion());
		}
		return reunionesConvertidas;
	}

	public static ArrayList<Reuniones> getReunionesByUserIDSemanaActual(int idUser) {
		LocalDate hoy = LocalDate.now();
		LocalDate inicioSemana = hoy.with(DayOfWeek.MONDAY);
		LocalDate finSemana = inicioSemana.plusDays(7);

		Timestamp inicio = Timestamp.valueOf(inicioSemana.atStartOfDay());
		Timestamp fin = Timestamp.valueOf(finSemana.atStartOfDay());

		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
		String hql = "from Reuniones where (usersByAlumnoId.id = :userID or usersByProfesorId.id = :userID) "
				+ "and fecha >= :inicioSemana and fecha < :finSemana order by fecha";
		Query<Reuniones> q = session.createQuery(hql, Reuniones.class);
		q.setParameter("userID", idUser);
		q.setParameter("inicioSemana", inicio);
		q.setParameter("finSemana", fin);
		ArrayList<Reuniones> reunionesConvertidas = new ArrayList<Reuniones>();
		for (Reuniones reunion : q.list()) {
			reunionesConvertidas.add(reunion.convertirReunion());
		}
		return reunionesConvertidas;
	}
	public Reuniones crearReunion() {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Transaction tx = null;
		try (Session session = sesion.openSession()) {
			tx = session.beginTransaction();
			Users alumno = new Users(getUsersByAlumnoId().getId()).getUsuarioPorID();
			Users profesor =  new Users(getUsersByProfesorId().getId()).getUsuarioPorID();
			setUsersByAlumnoId(alumno);
			setUsersByProfesorId(profesor);
			Timestamp now = new Timestamp(System.currentTimeMillis());
			if (getCreatedAt() == null) {
				setCreatedAt(now);
			}
			setUpdatedAt(now);
			if (getEstadoEnum() == null) {
				setEstado(EstadoReunion.PENDIENTE);
			}
			session.persist(this);
			tx.commit();
			return convertirReunion();
		} catch (Exception e) {
			if (tx != null) {
				tx.rollback();
			}
			throw e;
		}
	}

	public Reuniones cambiarEstadoReunion(EstadoReunion nuevoEstado) {
		if (getIdReunion() == null) {
			throw new IllegalStateException("Id de reunión obligatorio para actualizar estado");
		}
		if (nuevoEstado == null) {
			throw new IllegalArgumentException("El nuevo estado no puede ser nulo");
		}
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Transaction tx = null;
		try (Session session = sesion.openSession()) {
			tx = session.beginTransaction();
			Reuniones reunion = session.get(Reuniones.class, getIdReunion());
			if (reunion == null) {
				throw new RuntimeException("Reunión no encontrada con id: " + getIdReunion());
			}
			reunion.setEstado(nuevoEstado);
			reunion.setUpdatedAt(new Timestamp(System.currentTimeMillis()));
			session.merge(reunion);
			tx.commit();
			return reunion.convertirReunion();
		} catch (Exception e) {
			if (tx != null) {
				tx.rollback();
			}
			throw e;
		}
	}

    public void eliminarReunion() {
        if (getIdReunion() == null) {
            throw new IllegalStateException("Id de reunión obligatorio para eliminar");
        }
        SessionFactory sesion = HibernateUtil.getSessionFactory();
        Transaction tx = null;
        try (Session session = sesion.openSession()) {
            tx = session.beginTransaction();
            Reuniones reunion = session.get(Reuniones.class, getIdReunion());
            if (reunion == null) {
                throw new RuntimeException("Reunión no encontrada con id: " + getIdReunion());
            }
            session.remove(reunion);
            tx.commit();
        } catch (Exception e) {
            if (tx != null) {
                tx.rollback();
            }
            throw e;
        }
    }
}
