package modelo;
// Generated 13 ene 2026, 8:47:05 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.ArrayList;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.query.Query;
import org.hibernate.Transaction;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.reto2.elorserv.HibernateUtil;

/**
 * Reuniones generated by hbm2java
 */
public class Reuniones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idReunion;
	private Users usersByAlumnoId;
	private Users usersByProfesorId;
	private String estado;
	private String estadoEus;
	private String idCentro;
	private String titulo;
	private String asunto;
	private String aula;
	private Timestamp fecha;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	private Centros centro;

	public enum EstadoReunion {
		PENDIENTE("pendiente"),
		ACEPTADA("aceptada"),
		DENEGADA("denegada"),
		CONFLICTO("conflicto");

		private final String value;

		EstadoReunion(String value) {
			this.value = value;
		}

		public String getValue() {
			return value;
		}

		public static EstadoReunion fromValue(String value) {
			if (value == null || value.isBlank()) {
				return null;
			}
			for (EstadoReunion estado : values()) {
				if (estado.value.equalsIgnoreCase(value)) {
					return estado;
				}
			}
			throw new IllegalArgumentException("Estado de reunión desconocido: " + value);
		}
	}

	public Reuniones() {
	}

	public Reuniones(int idReunion) {
		this.idReunion = idReunion;
	}

	public Reuniones(Users usersByAlumnoId, Users usersByProfesorId, String estado, String estadoEus, String idCentro,
			String titulo, String asunto, String aula, Timestamp fecha, Timestamp createdAt, Timestamp updatedAt) {
		this.usersByAlumnoId = usersByAlumnoId;
		this.usersByProfesorId = usersByProfesorId;
		this.estado = estado;
		this.estadoEus = estadoEus;
		this.idCentro = idCentro;
		this.titulo = titulo;
		this.asunto = asunto;
		this.aula = aula;
		this.fecha = fecha;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Reuniones(Reuniones otro) {
	    this.idReunion = otro.getIdReunion();
	    this.usersByAlumnoId = otro.getUsersByAlumnoId() != null ? new Users(otro.getUsersByAlumnoId()) : null;
	    this.usersByProfesorId = otro.getUsersByProfesorId() != null ? new Users(otro.getUsersByProfesorId()) : null;

	    this.estado = otro.getEstado();
	    this.estadoEus = otro.getEstadoEus();
	    this.idCentro = otro.getIdCentro();
	    this.titulo = otro.getTitulo();
	    this.asunto = otro.getAsunto();
	    this.aula = otro.getAula();
	    this.fecha = otro.getFecha();
	    this.createdAt = otro.getCreatedAt();
	    this.updatedAt = otro.getUpdatedAt();
	    this.centro = otro.getCentro() != null ? otro.getCentro() : null;
	}

	public Integer getIdReunion() {
		return this.idReunion;
	}

	public void setIdReunion(Integer idReunion) {
		this.idReunion = idReunion;
	}

	public Users getUsersByAlumnoId() {
		return this.usersByAlumnoId;
	}

	public void setUsersByAlumnoId(Users usersByAlumnoId) {
		this.usersByAlumnoId = usersByAlumnoId;
	}

	public Users getUsersByProfesorId() {
		return this.usersByProfesorId;
	}

	public void setUsersByProfesorId(Users usersByProfesorId) {
		this.usersByProfesorId = usersByProfesorId;
	}

	public String getEstado() {
		return this.estado;
	}

	public EstadoReunion getEstadoEnum() {
		return EstadoReunion.fromValue(this.estado);
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public void setEstado(EstadoReunion estadoEnum) {
		this.estado = estadoEnum != null ? estadoEnum.getValue() : null;
	}

	public String getEstadoEus() {
		return this.estadoEus;
	}

	public void setEstadoEus(String estadoEus) {
		this.estadoEus = estadoEus;
	}

	public String getIdCentro() {
		return this.idCentro;
	}

	public void setIdCentro(String idCentro) {
		this.idCentro = idCentro;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	public String getAula() {
		return this.aula;
	}

	public void setAula(String aula) {
		this.aula = aula;
	}

	public Timestamp getFecha() {
		return this.fecha;
	}

	public void setFecha(Timestamp fecha) {
		this.fecha = fecha;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}
	
	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}
	public Centros getCentro() {
		return this.centro;
	}

	public void setCentro(Centros centro) {
		this.centro = centro;
	}
	


	@Override
	public String toString() {
		return "Reuniones [idReunion=" + idReunion + ", usersByAlumnoId=" + usersByAlumnoId + ", usersByProfesorId="
				+ usersByProfesorId + ", estado=" + estado + ", estadoEus=" + estadoEus + ", idCentro=" + idCentro
				+ ", titulo=" + titulo + ", asunto=" + asunto + ", aula=" + aula + ", fecha=" + fecha + ", createdAt="
				+ createdAt + ", updatedAt=" + updatedAt + ", centro=" + centro + "]";
	}

	@JsonIgnore
	public static ArrayList<Reuniones> getAllReuniones() {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
		String hql = "from Reuniones";
		Query<Reuniones> q = session.createQuery(hql, Reuniones.class);
		ArrayList<Reuniones> reunionesConvertidas = new ArrayList<Reuniones
				>();
		for (Reuniones reunion : q.list()) {
			reunionesConvertidas.add(new Reuniones(reunion));
		}
		return reunionesConvertidas;
		
	}
	public static ArrayList<Reuniones> getReunionesByUserID(int idUser) {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
		String hql = "from Reuniones where usersByAlumnoId = "+ idUser + " or usersByProfesorId = "+idUser;
		Query<Reuniones> q = session.createQuery(hql, Reuniones.class);
		ArrayList<Reuniones> reunionesConvertidas = new ArrayList<Reuniones
				>();
		for (Reuniones reunion : q.list()) {
			reunionesConvertidas.add(new Reuniones(reunion));
		}
		return reunionesConvertidas;
	}

	public static ArrayList<Reuniones> getReunionesByUserIDSemanaActual(int idUser) {
		LocalDate hoy = LocalDate.now();
		LocalDate inicioSemana = hoy.with(DayOfWeek.MONDAY);
		LocalDate finSemana = inicioSemana.plusDays(7);

		Timestamp inicio = Timestamp.valueOf(inicioSemana.atStartOfDay());
		Timestamp fin = Timestamp.valueOf(finSemana.atStartOfDay());

		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
		String hql = "from Reuniones where (usersByAlumnoId = "+idUser+ " or usersByProfesorId = "+ idUser+") "
				+ "and fecha >= :inicioSemana and fecha < :finSemana order by fecha";
		Query<Reuniones> q = session.createQuery(hql, Reuniones.class);
		q.setParameter("inicioSemana", inicio);
		q.setParameter("finSemana", fin);
		ArrayList<Reuniones> reunionesConvertidas = new ArrayList<Reuniones>();
		for (Reuniones reunion : q.list()) {
			reunionesConvertidas.add(new Reuniones(reunion));
		}
		return reunionesConvertidas;
	}
	public Reuniones crearReunion() {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Transaction tx = null;
		try (Session session = sesion.openSession()) {
			tx = session.beginTransaction();
			Users alumno = getUsersByAlumnoId().getUsuarioPorID();
			Users profesor =  getUsersByProfesorId().getUsuarioPorID();
			setUsersByAlumnoId(alumno);
			setUsersByProfesorId(profesor);
			Timestamp now = new Timestamp(System.currentTimeMillis());
			if (getCreatedAt() == null) {
				setCreatedAt(now);
			}
			setUpdatedAt(now);
			if (getEstadoEnum() == null) {
				setEstado(EstadoReunion.PENDIENTE);
			}
			session.persist(this);
			tx.commit();
			return this;
		} catch (Exception e) {
			System.out.println(this);
			System.out.println(e.getMessage());
			if (tx != null) {
				tx.rollback();
			}
			throw e;
		}
	}

	public Reuniones cambiarEstadoReunion(EstadoReunion nuevoEstado) {
		if (getIdReunion() == null) {
			throw new IllegalStateException("Id de reunión obligatorio para actualizar estado");
		}
		if (nuevoEstado == null) {
			throw new IllegalArgumentException("El nuevo estado no puede ser nulo");
		}
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Transaction tx = null;
		try (Session session = sesion.openSession()) {
			tx = session.beginTransaction();
			Reuniones reunion = session.get(Reuniones.class, getIdReunion());
			if (reunion == null) {
				throw new RuntimeException("Reunión no encontrada con id: " + getIdReunion());
			}
			reunion.setEstado(nuevoEstado);
			reunion.setUpdatedAt(new Timestamp(System.currentTimeMillis()));
			session.merge(reunion);
			tx.commit();
			Reuniones reunionCreada = session.get(Reuniones.class, getIdReunion());
			return new Reuniones(reunionCreada);
		} catch (Exception e) {
			if (tx != null) {
				tx.rollback();
			}
			throw e;
		}
	}

    public void eliminarReunion() {
        if (getIdReunion() == null) {
            throw new IllegalStateException("Id de reunión obligatorio para eliminar");
        }
        SessionFactory sesion = HibernateUtil.getSessionFactory();
        Transaction tx = null;
        try (Session session = sesion.openSession()) {
            tx = session.beginTransaction();
            Reuniones reunion = session.get(Reuniones.class, getIdReunion());
            if (reunion == null) {
                throw new RuntimeException("Reunión no encontrada con id: " + getIdReunion());
            }
            session.remove(reunion);
            tx.commit();
        } catch (Exception e) {
            if (tx != null) {
                tx.rollback();
            }
            throw e;
        }
    }
}
