package modelo;
// Generated 13 ene 2026, 8:47:05 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.query.Query;
import org.springframework.web.bind.annotation.PathVariable;

import com.fasterxml.jackson.annotation.JsonIgnore;

import metodos.HibernateUtil;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Tipos tipos;
	private String email;
	private String username;
	private String password;
	private String nombre;
	private String apellidos;
	private String dni;
	private String direccion;
	private String telefono1;
	private String telefono2;
	private String argazkiaUrl;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	@JsonIgnore
	private Set<Matriculaciones> matriculacioneses = new HashSet<Matriculaciones>(0);
	@JsonIgnore
	private Set<Reuniones> reunionesesForAlumnoId = new HashSet<Reuniones>(0);
	@JsonIgnore
	private Set<Horarios> horarioses = new HashSet<Horarios>(0);
	@JsonIgnore
	private Set<Reuniones> reunionesesForProfesorId = new HashSet<Reuniones>(0);

	
	
	public Users() {
		super();
	}

	public Users(Integer id, String username, String email) {
		this.id = id;
		this.username = username;
		this.email = email;
	}

	public Users(Tipos tipos, String email, String username, String password) {
		this.tipos = tipos;
		this.email = email;
		this.username = username;
		this.password = password;
	}

	public Users(Tipos tipos, String email, String username, String password, String nombre, String apellidos,
			String dni, String direccion, String telefono1, String telefono2, String argazkiaUrl, Timestamp createdAt,
			Timestamp updatedAt, Set<Matriculaciones>  matriculacioneses, Set<Reuniones> reunionesesForAlumnoId, Set<Horarios> horarioses,
			Set<Reuniones>  reunionesesForProfesorId) {
		this.tipos = tipos;
		this.email = email;
		this.username = username;
		this.password = password;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.dni = dni;
		this.direccion = direccion;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.argazkiaUrl = argazkiaUrl;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.matriculacioneses = matriculacioneses;
		this.reunionesesForAlumnoId = reunionesesForAlumnoId;
		this.horarioses = horarioses;
		this.reunionesesForProfesorId = reunionesesForProfesorId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Tipos getTipos() {
		return this.tipos;
	}

	public void setTipos(Tipos tipos) {
		this.tipos = tipos;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	public String getArgazkiaUrl() {
		return this.argazkiaUrl;
	}

	public void setArgazkiaUrl(String argazkiaUrl) {
		this.argazkiaUrl = argazkiaUrl;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<Matriculaciones> getMatriculacioneses() {
		return this.matriculacioneses;
	}

	public void setMatriculacioneses(Set<Matriculaciones> matriculacioneses) {
		this.matriculacioneses = matriculacioneses;
	}

	public Set<Reuniones> getReunionesesForAlumnoId() {
		return this.reunionesesForAlumnoId;
	}

	public void setReunionesesForAlumnoId(Set<Reuniones> reunionesesForAlumnoId) {
		this.reunionesesForAlumnoId = reunionesesForAlumnoId;
	}

	public Set<Horarios> getHorarioses() {
		return this.horarioses;
	}

	public void setHorarioses(Set<Horarios> horarioses) {
		this.horarioses = horarioses;
	}

	public Set<Reuniones>  getReunionesesForProfesorId() {
		return this.reunionesesForProfesorId;
	}

	public void setReunionesesForProfesorId(Set<Reuniones>  reunionesesForProfesorId) {
		this.reunionesesForProfesorId = reunionesesForProfesorId;
	}
	public static Users getUsuarioUsernameContraseña(String username, String password) {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
		String hql = "from Users where username = ?1 and password = ?2";
		Query<Users> q = session.createQuery(hql, Users.class);
		q.setParameter(1, username);
		q.setParameter(2, password);
		return q.uniqueResult();
	}
	public static Users getUsuarioPorID(int id) {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
		String hql = "from Users where id = ?1";
		Query<Users> q = session.createQuery(hql, Users.class);
		q.setParameter(1, id);
		return q.uniqueResult();
	}
	
	public static ArrayList<Users> getAllUsuarios() {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
		String hql = "from Users";
		Query<Users> q = session.createQuery(hql, Users.class);
		return new ArrayList<Users>(q.list());
	}


}
