package modelo;
// Generated 13 ene 2026, 8:47:05 by Hibernate Tools 6.5.1.Final

import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Base64;
import java.util.HashSet;
import java.util.Set;

import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.query.Query;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.reto2.elorserv.HibernateUtil;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private static final String AES_TRANSFORMATION = "AES/ECB/PKCS5Padding";
	private static final int AES_KEY_LENGTH = 16;
	private static final String ENV_KEY = System.getenv().getOrDefault("ELOR_AES_KEY","ELORG6RETO2");
	
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Tipos tipos;
	private String email;
	private String username;
	private String password;
	private String nombre;
	private String apellidos;
	private String dni;
	private String direccion;
	private String telefono1;
	private String telefono2;
	private String argazkiaUrl;
	private Timestamp createdAt;
	private Timestamp updatedAt;
	@JsonIgnore
	private Set<Matriculaciones> matriculacioneses = new HashSet<Matriculaciones>(0);
	@JsonIgnore
	private Set<Reuniones> reunionesesForAlumnoId = new HashSet<Reuniones>(0);
	@JsonIgnore
	private Set<Horarios> horarioses = new HashSet<Horarios>(0);
	@JsonIgnore
	private Set<Reuniones> reunionesesForProfesorId = new HashSet<Reuniones>(0);

	public Users() {
		super();
	}

	public Users(Integer id) {
		super();
		this.id= id;
	}
	public Users(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public Users(Integer id, String username, String email) {
		this.id = id;
		this.username = username;
		this.email = email;
	}

	public Users(Tipos tipos, String email, String username, String password) {
		this.tipos = tipos;
		this.email = email;
		this.username = username;
		this.password = password;
	}

	public Users(Tipos tipos, String email, String username, String password, String nombre, String apellidos,
			String dni, String direccion, String telefono1, String telefono2, String argazkiaUrl, Timestamp createdAt,
			Timestamp updatedAt, Set<Matriculaciones> matriculacioneses, Set<Reuniones> reunionesesForAlumnoId,
			Set<Horarios> horarioses, Set<Reuniones> reunionesesForProfesorId) {
		this.tipos = tipos;
		this.email = email;
		this.username = username;
		this.password = password;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.dni = dni;
		this.direccion = direccion;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.argazkiaUrl = argazkiaUrl;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.matriculacioneses = matriculacioneses;
		this.reunionesesForAlumnoId = reunionesesForAlumnoId;
		this.horarioses = horarioses;
		this.reunionesesForProfesorId = reunionesesForProfesorId;
	}

	public Users(Integer id,String email, String username, String password, String nombre, String apellidos, String dni,
			String direccion, String telefono1, String telefono2, String argazkiaUrl, Timestamp createdAt,
			Timestamp updatedAt, Tipos tipos) {
		this.id = id;
		this.email = email;
		this.username = username;
		this.password = password;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.dni = dni;
		this.direccion = direccion;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.argazkiaUrl = argazkiaUrl;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.tipos = tipos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Tipos getTipos() {
		return this.tipos;
	}

	public void setTipos(Tipos tipos) {
		this.tipos = tipos;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

	public String getArgazkiaUrl() {
		return this.argazkiaUrl;
	}

	public void setArgazkiaUrl(String argazkiaUrl) {
		this.argazkiaUrl = argazkiaUrl;
	}

	public Timestamp getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Timestamp createdAt) {
		this.createdAt = createdAt;
	}

	public Timestamp getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Timestamp updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set<Matriculaciones> getMatriculacioneses() {
		return this.matriculacioneses;
	}

	public void setMatriculacioneses(Set<Matriculaciones> matriculacioneses) {
		this.matriculacioneses = matriculacioneses;
	}

	public Set<Reuniones> getReunionesesForAlumnoId() {
		return this.reunionesesForAlumnoId;
	}

	public void setReunionesesForAlumnoId(Set<Reuniones> reunionesesForAlumnoId) {
		this.reunionesesForAlumnoId = reunionesesForAlumnoId;
	}

	public Set<Horarios> getHorarioses() {
		return this.horarioses;
	}

	public void setHorarioses(Set<Horarios> horarioses) {
		this.horarioses = horarioses;
	}

	public Set<Reuniones> getReunionesesForProfesorId() {
		return this.reunionesesForProfesorId;
	}
	public void setReunionesesForProfesorId(Set<Reuniones> reunionesesForProfesorId) {
		this.reunionesesForProfesorId = reunionesesForProfesorId;
	}
	@Override
	public String toString() {
		return "Users [id=" + id + ", tipos=" + tipos + ", email=" + email + ", username=" + username + ", password="
				+ password + ", nombre=" + nombre + ", apellidos=" + apellidos + ", dni=" + dni + ", direccion="
				+ direccion + ", telefono1=" + telefono1 + ", telefono2=" + telefono2 + ", argazkiaUrl=" + argazkiaUrl
				+ ", createdAt=" + createdAt + ", updatedAt=" + updatedAt + "]";
	}
	public Users convertirUsuario() {
		Tipos t = new Tipos(getTipos().getId(), getTipos().getName(),getTipos().getNameEu());
		String usernameDescifrado = descifrar(getUsername());
		return new Users(getId(),getEmail(), usernameDescifrado, getPassword(), getNombre(), getApellidos(), getDni(),
				getDireccion(), getTelefono1(), getTelefono2(), getArgazkiaUrl(), getCreatedAt(),
				getUpdatedAt(),t);
	}


	
	public Users iniciarSesion() {
        if (username == null || username.trim().isEmpty()
                || password == null || password.trim().isEmpty()) {
            throw new IllegalArgumentException("Usuario o contraseña incorrectos");
        }
        try {
            Users user = getUsuarioUsernameContraseña();
            if (user == null) {
                throw new RuntimeException("Credenciales inválidas");
            }
            return user;

        } catch (Exception e) {
            throw new RuntimeException("Credenciales inválidas");
        }
    }
	@JsonIgnore
	public Users getUsuarioUsernameContraseña() {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
		String usernameCifrado = cifrar(username);
		String passwordCifrado = cifrar(password);
		String hql = "from Users where username = ?1 and password = ?2";
		Query<Users> q = session.createQuery(hql, Users.class);
		q.setParameter(1, usernameCifrado);
		q.setParameter(2, passwordCifrado);
		Users resultado = q.uniqueResult();
		return resultado != null ? resultado.convertirUsuario() : null;
	}
	@JsonIgnore
	public Users getUsuarioPorID() {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
		String hql = "from Users where id = ?1";
		Query<Users> q = session.createQuery(hql, Users.class);
		q.setParameter(1, getId());
		Users u = q.uniqueResult();
		return q.uniqueResult().convertirUsuario();
	}

	public static ArrayList<Users> getAllUsuarios() {
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		Session session = sesion.openSession();
		String hql = "from Users";
		Query<Users> q = session.createQuery(hql, Users.class);
		ArrayList<Users> a = new ArrayList<Users>(q.list());
		ArrayList<Users> usuariosConvertidos = new ArrayList<Users>();
		for (Users usuario : a) {
			usuariosConvertidos.add(usuario.convertirUsuario());
		}
		return usuariosConvertidos;
	}
	
	public Users crearUsuario() {
 	    SessionFactory sesion = HibernateUtil.getSessionFactory();
 	    try (Session session = sesion.openSession()) {
 	        Transaction tx = session.beginTransaction();
	        String usernameNormalizado = getUsername().trim().toLowerCase();
	        asegurarUsernameDisponible(usernameNormalizado, null);
	        // Cifrado simétrico
	        setUsername(cifrar(usernameNormalizado));
 	        setPassword(cifrar(getPassword()));
 	        setId(null);
 	        
 	        // Timestamps
 	        Timestamp now = new Timestamp(System.currentTimeMillis());
 	        setCreatedAt(now);
 	        setUpdatedAt(now);
 	        session.persist(this);
 	        tx.commit();
 	        return convertirUsuario();
 	    } catch (Exception e) {
 	        e.printStackTrace(); 
 	        throw e;
 	    }
 	}

	public Users actualizarUsuario() {
		if (getId() == null) {
			throw new IllegalArgumentException("Id obligatorio para actualizar usuario");
		}
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		try (Session session = sesion.openSession()) {
			Transaction tx = session.beginTransaction();
			Users existente = session.get(Users.class, getId());
			if (existente == null) {
				throw new RuntimeException("Usuario no encontrado con id: " + getId());
			}
			String usernameNormalizado = getUsername().trim().toLowerCase();
			asegurarUsernameDisponible(usernameNormalizado, existente.getId());
 			if (getTipos() != null) {
 				Tipos tipoGestionado = session.get(Tipos.class, getTipos().getId());
 				existente.setTipos(tipoGestionado);
 			}
 			existente.setEmail(getEmail());
			existente.setUsername(cifrar(getUsername()));
			existente.setUsername(cifrar(usernameNormalizado));
 			existente.setNombre(getNombre());
 			existente.setApellidos(getApellidos());
 			existente.setDni(getDni());
 			existente.setDireccion(getDireccion());
 			existente.setTelefono1(getTelefono1());
 			existente.setTelefono2(getTelefono2());
 			existente.setArgazkiaUrl(getArgazkiaUrl());
 			existente.setUpdatedAt(new Timestamp(System.currentTimeMillis()));
 			session.merge(existente);
 			tx.commit();
 			return existente.convertirUsuario();
		} catch (Exception e) {
			throw e;
		}
	}

	public Users cambiarPassword(String nuevaPassword) {
		if (getId() == null) {
			throw new IllegalArgumentException("Id obligatorio para cambiar la contraseña");
		}
		if (nuevaPassword == null || nuevaPassword.isBlank()) {
			throw new IllegalArgumentException("La nueva contraseña no puede estar vacía");
		}
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		try (Session session = sesion.openSession()) {
			Transaction tx = session.beginTransaction();
			Users existente = session.get(Users.class, getId());
			if (existente == null) {
				throw new RuntimeException("Usuario no encontrado con id: " + getId());
			}
			existente.setPassword(cifrar(nuevaPassword));
			existente.setUpdatedAt(new Timestamp(System.currentTimeMillis()));
			session.merge(existente);
			tx.commit();
			return existente.convertirUsuario();
		} catch (Exception e) {
			throw e;
		}
	}
	public void borrarUsuario() {
	    SessionFactory sesion = HibernateUtil.getSessionFactory();
	    try (Session session = sesion.openSession()) {
	        Transaction tx = null;
	        try {
	            tx = session.beginTransaction();
	            Users u = session.get(Users.class, getId());
	            if (u == null) {
	                throw new RuntimeException("Usuario no encontrado con id: " + id);
	            }
	            session.remove(u);
	            tx.commit();
	        } catch (Exception e) {
	            if (tx != null) tx.rollback();
	            throw e;
	        }
	    } catch (Exception e) {
	        
	    }

	}

	private static void asegurarUsernameDisponible(String username, Integer excluirId) {
		if (usernameExiste(username, excluirId)) {
			throw new IllegalArgumentException("El nombre de usuario ya está en uso");
		}
	}

	public static boolean usernameExiste(String username, Integer excluirId) {
		String usernameNormalizado = username.trim().toLowerCase();
		SessionFactory sesion = HibernateUtil.getSessionFactory();
		try (Session session = sesion.openSession()) {
			String hql = "select count(u.id) from Users u where u.username = :username";
			if (excluirId != null) {
				hql= hql+" and u.id <> :excluirId";
			}
			Query<Long> q = session.createQuery(hql.toString(), Long.class);
			q.setParameter("username", cifrar(usernameNormalizado));
			if (excluirId != null) {
				q.setParameter("excluirId", excluirId);
			}
			Long count = q.uniqueResult();
			return count != null && count > 0;
		}
	}


 	public static String cifrar(String valor) {
 		if (valor == null) {
 			return null;
 		}
 		try {
 			Cipher cipher = Cipher.getInstance(AES_TRANSFORMATION);
 			cipher.init(Cipher.ENCRYPT_MODE, key());
 			byte[] cifrado = cipher.doFinal(valor.getBytes(StandardCharsets.UTF_8));
 			return Base64.getEncoder().encodeToString(cifrado);
 		} catch (Exception e) {
 			throw new RuntimeException("Error cifrando valor", e);
 		}
 	}
 
 	public static String descifrar(String valor) {
 		if (valor == null) {
 			return null;
 		}
 		try {
 			Cipher cipher = Cipher.getInstance(AES_TRANSFORMATION);
 			cipher.init(Cipher.DECRYPT_MODE, key());
 			byte[] decodificado = Base64.getDecoder().decode(valor);
 			byte[] descifrado = cipher.doFinal(decodificado);
 			return new String(descifrado, StandardCharsets.UTF_8);
 		} catch (Exception e) {
 			throw new RuntimeException("Error descifrando valor", e);
 		}
 	}
 
 	@JsonIgnore
 	private static SecretKeySpec key() {
		byte[] keyBytes = ENV_KEY.getBytes(StandardCharsets.UTF_8);
		byte[] normalized = new byte[AES_KEY_LENGTH];
		for (int i = 0; i < AES_KEY_LENGTH; i++) {
			normalized[i] = i < keyBytes.length ? keyBytes[i] : 0;
		}
		return new SecretKeySpec(normalized, "AES");
	}
 }
